version: '3'

networks:
  nginx-php74-postgres-node:

services:
  nginx-service:
    image: nginx:stable-alpine
    container_name: nginx-container
    ports:
      - "8080:80"
    volumes:
      - ./app:/var/www/project
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php74-service
      - postgres-service
    networks:
      - nginx-php74-postgres-node

  php74-service:
    build:
      context: .
      dockerfile: ./php/Dockerfile
    container_name: php74-container
    depends_on:
      - postgres-service
    ports:
      - "9001:9001"
    volumes:
      - ./app:/var/www/project
    networks:
      - nginx-php74-postgres-node

  postgres-service:
    image: postgres
    container_name: postgres-container
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    restart: always # always restart unless stopped manually
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: rest-api-php
    networks:
      - nginx-php74-postgres-node

  node-service:
    image: node:14
    container_name: node-container
    volumes:
      - ./app:/var/www/project
    working_dir: /var/www/project
    networks:
      - nginx-php74-postgres-node